const IndianBankList = [
  { label: "Allahabad Bank", value: "Allahabad Bank" },
  { label: "Andhra Bank", value: "Andhra Bank" },
  { label: "DBS Bank", value: "DBS Bank" },
  { label: "Uttarakhand Gramin Bank", value: "Uttarakhand Gramin Bank" },
  { label: "Equitas Small Finance Bank", value: "Equitas Small Finance Bank" },
  { label: "Indian Bank", value: "Indian Bank" },
  { label: " Nainital Bank", value: " Nainital Bank" },
  { label: "Airtel Bank", value: "Airtel Bank" },
  { label: "Axis Bank", value: "Axis Bank" },
  { label: "Bank of Bahrain and Kuwait", value: "Bank of Bahrain and Kuwait" },
  {
    label: "Bank of Baroda - Corporate Banking",
    value: "Bank of Baroda - Corporate Banking",
  },
  {
    label: "Bank of Baroda - Retail Banking",
    value: "Bank of Baroda - Retail Banking",
  },
  { label: "Bank of India", value: "Bank of India" },
  { label: "Bank of Maharashtra", value: "Bank of Maharashtra" },
  { label: "Canara Bank", value: "Canara Bank" },
  { label: "Central Bank of India", value: "Central Bank of India" },
  { label: "City Union Bank", value: "City Union Bank" },
  { label: "Corporation Bank", value: "Corporation Bank" },
  { label: "Deutsche Bank", value: "Deutsche Bank" },
  { label: "Development Credit Bank", value: "Development Credit Bank" },
  { label: "Dhanlaxmi Bank", value: "Dhanlaxmi Bank" },
  { label: "Federal Bank", value: "Federal Bank" },
  { label: "HDFC Bank", value: "HDFC Bank" },
  { label: "ICICI Bank", value: "ICICI Bank" },
  { label: "IDBI Bank", value: "IDBI Bank" },
  { label: "Indian Bank", value: "Indian Bank" },
  { label: "Indian Overseas Bank", value: "Indian Overseas Bank" },
  { label: "IndusInd Bank", value: "IndusInd Bank" },
  { label: "ING Vysya Bank", value: "ING Vysya Bank" },
  { label: "Jammu and Kashmir Bank", value: "Jammu and Kashmir Bank" },
  { label: "Karnataka Bank Ltd", value: "Karnataka Bank Ltd" },
  { label: "Karur Vysya Bank", value: "Karur Vysya Bank" },
  { label: "Kotak Bank", value: "Kotak Bank" },
  { label: "Laxmi Vilas Bank", value: "Laxmi Vilas Bank" },
  { label: "Oriental Bank of Commerce", value: "Oriental Bank of Commerce" },
  {
    label: "Punjab National Bank - Corporate Banking",
    value: "Punjab National Bank - Corporate Banking",
  },
  {
    label: "Punjab National Bank - Retail Banking",
    value: "Punjab National Bank - Retail Banking",
  },
  { label: "Punjab & Sind Bank", value: "Punjab & Sind Bank" },
  {
    label: "Shamrao Vitthal Co-operative Bank",
    value: "Shamrao Vitthal Co-operative Bank",
  },
  { label: "South Indian Bank", value: "South Indian Bank" },
  {
    label: "State Bank of Bikaner & Jaipur",
    value: "State Bank of Bikaner & Jaipur",
  },
  { label: "State Bank of Hyderabad", value: "State Bank of Hyderabad" },
  { label: "State Bank of India", value: "State Bank of India" },
  { label: "State Bank of Mysore", value: "State Bank of Mysore" },
  { label: "State Bank of Patiala", value: "State Bank of Patiala" },
  { label: "State Bank of Travancore", value: "State Bank of Travancore" },
  { label: "Syndicate Bank", value: "Syndicate Bank" },
  {
    label: "Tamilnad Mercantile Bank Ltd.",
    value: "Tamilnad Mercantile Bank Ltd.",
  },
  { label: "UCO Bank", value: "UCO Bank" },
  { label: "Union Bank of India", value: "Union Bank of India" },
  { label: "United Bank of India", value: "United Bank of India" },
  { label: "Vijaya Bank", value: "Vijaya Bank" },
  { label: "Yes Bank Ltd", value: "Yes Bank Ltd" },
];

export default IndianBankList;
